### PR TITLE
meson: assume non-managarm platforms are standalone

### PR DESCRIPTION
**Pull request by cleanbaja**

### CODE REVIEW

**Review by qookei — APPROVED** [review]

**Comment by cleanbaja** [comment]
yeah, but a new OS could get added to the if statement if required

**Comment by cleanbaja** [comment]
at the end of the day, the if statement is to seperate managarm from non-managarm

**Comment by ArsenArsen** [comment]
No, it's to distinguish between many OS values.  If a new OS exists, it should be a new value.  Currently accepted OS values should be `managarm` and `bare`.  As a result of this change, they are any of infinitely many string values, all but one mapping to the same result.

**Comment by ArsenArsen** [comment]
That's only true currently.  Accepting unknown values here, where there is special behavior involved sometimes, means not accurately reporting support.  On the other hand, maybe that's fine, because maybe bare is a sane level of support..  I'm not sure now.

**Comment by ikbenlike** [comment]
Wouldn't it be possible to emit a warning and still default to bare?

**Pull request merged**
